name: 'OpenBSD-vm'
description: 'Run CI in OpenBSD for GitHub Actions'
inputs:
  osname:
    description: 'The OS name'
    required: false
    default: 'OpenBSD'
  prepare:
    description: 'Install some tools before CI runs'
    required: false
  run:
    description: 'The CI command to run'
    required: true
  release:
    description: 'The release version of OpenBSD vm'
    required: false
  arch:
    description: 'The cpu architecture of OpenBSD vm'
    required: false
  envs:
    description: 'The envs to pass into OpenBSD vm'
    required: false
  mem:
    description: 'Set the memory size of the vm'
    required: false
    default: '6144'
  cpu:
    description: 'Set the cpu cores of the vm'
    required: false
  nat:
    description: 'The NAT ports to OpenBSD vm'
    required: false
  usesh:
    description: 'Use sh instead of the default shell: csh'
    required: false
  sync:
    description: 'How to synchronize the source code to/from the VM, Values can be:  rsync(default), and sshfs'
    required: false
  copyback:
    description: 'whether or not to copy the build result repo back from the VM to the host Mac OS, defalt is True'
    required: false
  debug:
    description: 'output debug message'
    required: false
branding:
  icon: 'activity'  
  color: 'green'

runs:
  using: 'node20'
  main: 'index.js'
